name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Poetry setup
      # You may pin to the exact commit or the version.
      # uses: ClementWalter/poetry-action@845abd0cfcc6671c045a2f9df189360bb73e64c4
      uses: ClementWalter/poetry-action@v1
    - name: Analysing the code with pylint
      run: |
        pylint --fail-under=6.0 $(git ls-files '*.py')
